# Config file for automatic testing at travis-ci.org

language: python
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py34

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install tox

# command to run tests, e.g. python setup.py test
# script: py.test tests
script: tox -e $TOX_ENV
