# Config file for automatic testing at travis-ci.org

language: python
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install tox

# command to run tests, e.g. python setup.py test
# script: py.test tests
script: tox
after_failure: cat .tox/log/tox-*.log
